/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qci_ndksample2_MainActivity */

#ifndef _Included_com_qci_ndksample2_MainActivity
#define _Included_com_qci_ndksample2_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qci_ndksample2_MainActivity
 * Method:    getStringFromJNI1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qci_ndksample2_MainActivity_getStringFromJNI1
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
