/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qci_ndksample2_MainActivity2 */

#ifndef _Included_com_qci_ndksample2_MainActivity2
#define _Included_com_qci_ndksample2_MainActivity2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qci_ndksample2_MainActivity2
 * Method:    getStringFromJNI2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qci_ndksample2_MainActivity2_getStringFromJNI2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
